# ports are given dictionary
# whose key is port id,
# and value is port address
din_ports:
  - 72
  - 73
  - 74
  - 75
  - 76
  - 77
  - 78
  - 79

dout_ports:
  - 105
  - 106
  - 107
  - 108
  - 109
  - 110
  - 111
  - 112
